conLev_3
NCAR/GeoCAT-examples pull request #211
Opened 2020-08-04 21:26 UTC by hCraker

Closes #210 
![image](https://user-images.githubusercontent.com/42781301/89346798-a5d6ee00-d677-11ea-978c-6628de14c3fe.png)

2020-08-04 22:44 UTC, michaelavs commented on Plots/Contours/NCL_conLev_3.py
> +gvutil.set_titles_and_labels(ax, maintitle="Explaination of Python contour levels")
typo: "explanation"

2020-08-04 22:47 UTC, michaelavs commented on Plots/Contours/NCL_conLev_3.py
> +from geocat.viz import cmaps as gvcmaps
```suggestion

```
Unused line

2020-08-04 22:48 UTC, michaelavs commented on Plots/Contours/NCL_conLev_3.py
> +
```suggestion
# Remove the degree symbol from tick labels
    ax.yaxis.set_major_formatter(LatitudeFormatter(degree_symbol=''))
    ax.xaxis.set_major_formatter(LongitudeFormatter(degree_symbol=''))
```

2020-08-06 15:44 UTC, michaelavs commented on Plots/Contours/NCL_conLev_3.py
> +# Contour-plot data (for line contours)
```suggestion

# Contour-plot data (for line contours)
```
Added white space for clarity

2020-08-06 15:44 UTC, michaelavs commented on Plots/Contours/NCL_conLev_3.py
> +y = y + 1 / num_lev  # Increment height once more for top label
```suggestion

y = y + 1 / num_lev  # Increment height once more for top label
```
Added white space for clarity

2020-09-05 02:32 UTC, erogluorhan requested changes
Code and plot are great! Correct a little typo mentioned in line please

2020-09-05 02:32 UTC, erogluorhan commented on Plots/Contours/NCL_conLev_3.py
> +NCL_conLev_4.py
typo, should be NCL_conLev_3, not 4.

2020-09-08 05:31 UTC, erogluorhan approved these changes

2020-09-08 05:31 UTC, merged