NCL_panel_9.py
NCAR/GeoCAT-examples pull request #306
Opened 2021-02-08 16:53 UTC by hCraker

Closes #284 
NCL Plot: https://www.ncl.ucar.edu/Applications/Images/panel_9_lg.png

![image](https://user-images.githubusercontent.com/42781301/107253334-35cd6a00-6a04-11eb-90b7-98926d84dc0f.png)

2021-02-08 16:56 UTC, hCraker commented
The original NCL script uses [wgt_runave_Wrap](https://www.ncl.ucar.edu/Document/Functions/Contributed/wgt_runave_Wrap.shtml) to calculate a running average for the data in the XY plot and then plots the resulting line. Is there an equivalent for this in Python yet? I have been unable to find something that is sufficient. @michaelavs @anissa111 Thanks!

2021-02-11 16:58 UTC, hCraker commented
I plotted the rolling average using `xarray.DataArray.rolling()` and it is similar to what is in the NCL plot, but the Python version is still jagged. The NCL version is also a weighted rolling average which hasn't been implemented in xarray yet. I'm going to continue to look for an improved way of doing this, but let me know if any of you have suggestions.

2021-02-12 15:13 UTC, hCraker commented
For future reference, the weighted rolling mean of xarray data can be calculated by first making a `DataArray` object with the weights. Then, call `xarray.rolling()` on the data in question. Using `.construct('window')` on the rolling object and then doing the dot product between it and the array of weights returns the weighted average. Note that the weights have to sum to 1 for this to work properly.

The edit to this [stack overflow post](https://stackoverflow.com/a/48512802) explains it better.

2021-02-12 15:22 UTC, hCraker commented
Current state of the plot using `make html`
![image](https://user-images.githubusercontent.com/42781301/107786760-42abcf80-6d1c-11eb-9cc9-c4383905c59e.png)

2021-02-12 15:26 UTC, hCraker commented
To properly fill the xy plot between y=0 and the data, I had to interpolate points and make that into a new array. Is there a better way to do this? I want to make sure this isn't terribly inefficient. I do this starting at line 118.

2021-02-16 22:18 UTC, michaelavs commented
I think everything looks good overall. I looked into your question about the xy plot and I couldn't find a better way to do the plotting, but I also don't have much of a problem with how the code is now as long as it doesn't take a super long time to build the html file (which it seems it isn't). The only thing I see needing changed is removing native_1 from the PR/branch because I think it's just sticking from another branch currently. After that, I should be ok with approving this PR!

2021-02-17 15:47 UTC, hCraker commented
Thanks for catching that @michaelavs. I accidentally did some work in the wrong branch. This PR should be good to go now.

2021-02-17 19:23 UTC, anissa111 requested changes
> To properly fill the xy plot between y=0 and the data, I had to interpolate points and make that into a new array. Is there a better way to do this? I want to make sure this isn't terribly inefficient. I do this starting at line 118.

There is actually a better way of doing this, though it essentially just does what you did on the back end. There's an option on the ```fill_between(...)``` call that will do this for you!

I've included the changes as suggestions below along with a typo I found. Other than that, this looks good to go, thank you!

2021-02-17 19:23 UTC, anissa111 commented on Plots/Panels/NCL_panel_9.py
> +# Retreive data points and interpolate to make the fillcolor more complete
```suggestion
# Retrieve data points and interpolate to make the fillcolor more complete
```

2021-02-17 19:23 UTC, anissa111 commented on Plots/Panels/NCL_panel_9.py
> +ax2.fill_between(x_interp, y_interp, where=y_interp < 0, color='blue')
```suggestion
ax2.fill_between(x, y, where=y > 0, color='red', interpolate=True)
ax2.fill_between(x, y, where=y < 0, color='blue', interpolate=True)
```

2021-02-17 19:23 UTC, anissa111 commented on Plots/Panels/NCL_panel_9.py
> +y_interp = np.interp(x_interp, x, y)
```suggestion
```

2021-02-17 20:33 UTC, hCraker commented
> There is actually a better way of doing this, though it essentially just does what you did on the back end. There's an option on the `fill_between(...)` call that will do this for you!
> 
> I've included the changes as suggestions below along with a typo I found. Other than that, this looks good to go, thank you!

Thank you @anissa111! I had no idea I could use that kwarg. This should be good to go once all of the checks complete.

2021-02-17 21:35 UTC, anissa111 approved these changes
This looks good, thank you for addressing those changes so quickly!

2021-02-17 21:40 UTC, michaelavs approved these changes
Looks good to me!

2021-02-23 22:06 UTC, merged