Text add 1
NCAR/GeoCAT-examples pull request #361
Opened 2021-06-09 17:38 UTC by Jiaqi-beep

- NCL Script: https://www.ncl.ucar.edu/Applications/Scripts/text_add_1.ncl
- NCL Plot: https://www.ncl.ucar.edu/Applications/Images/text_1_lg.png
- Issue: #343 
![Figure_1](https://user-images.githubusercontent.com/63561327/121402303-f1e96380-c916-11eb-8686-cfb733c3eaac.png)

2021-06-10 20:49 UTC, anissa111 requested changes
This looks good! Just a few minor comments below

2021-06-10 20:49 UTC, anissa111 commented on Plots/Line/NCL_text_add_1.py
> +===============
```suggestion
NCL_text_add_1.py
=================
```

2021-06-10 20:49 UTC, anissa111 commented on Plots/Line/NCL_text_add_1.py
> +plt.show()
```suggestion
# Show the plot
plt.tight_layout()
plt.show()
```

This will help remove some of the whitespace from around the figure

2021-06-10 20:49 UTC, anissa111 commented on Plots/Line/NCL_text_add_1.py
> +plt.plot(lon, uz.values, c='gray')
I think you should bump your linewidth down just a hair here to more closely replicate the original.

2021-06-10 20:53 UTC, michaelavs commented on Plots/Line/NCL_text_add_1.py
> +                             labelsize=12)
Maybe increase font size a little bit here to better replicate the NCL version

2021-06-11 14:42 UTC, Jiaqi-beep commented
updated.

2021-06-11 21:58 UTC, anissa111 approved these changes
Looks good, thank you!

2021-06-14 22:40 UTC, michaelavs approved these changes

2021-06-15 17:08 UTC, merged