Bar_1
NCAR/GeoCAT-examples pull request #364
Opened 2021-06-11 19:07 UTC by Jiaqi-beep

- NCL Script: https://www.ncl.ucar.edu/Applications/Scripts/bar_1.ncl
- NCL Plots: https://www.ncl.ucar.edu/Applications/Images/bar_1_1_lg.png, https://www.ncl.ucar.edu/Applications/Images/bar_1_2_lg.png, https://www.ncl.ucar.edu/Applications/Images/bar_1_3_lg.png
- Issue: #337 
![bar](https://user-images.githubusercontent.com/63561327/121737254-dbc5d980-cab5-11eb-9c95-1dbb6c401f49.png)

2021-06-11 19:08 UTC, Jiaqi-beep commented
Having some problems with the size

2021-06-11 19:23 UTC, anissa111 commented
> Having some problems with the size

Hello, what's going on?

2021-06-11 19:52 UTC, Jiaqi-beep commented
> > Having some problems with the size
> 
> Hello, what's going on?

The sizing wasn't right so I split subplots into three separate plots

2021-06-11 21:56 UTC, anissa111 requested changes
This looks good! See minor comments below, then I'll approve :)

2021-06-11 21:56 UTC, anissa111 commented on Plots/Bar/NCL_bar_1.py
> +                         and https://www.ncl.ucar.edu/Applications/Images/bar_1_3_lg.png
```suggestion
    - Original NCL plot: https://www.ncl.ucar.edu/Applications/Images/bar_1_1_lg.png, https://www.ncl.ucar.edu/Applications/Images/bar_1_2_lg.png and https://www.ncl.ucar.edu/Applications/Images/bar_1_3_lg.png
```

While it's ugly to have one really long line with a bunch of urls, the docs don't generate correctly if a line break is added:

![image](https://user-images.githubusercontent.com/38434768/121752179-d45dfa80-cacc-11eb-8462-02679f9fd309.png)

2021-06-11 21:56 UTC, anissa111 commented on Plots/Bar/NCL_bar_1.py
> +#dsoid = ds.DSOI_DEC
```suggestion
```

Remove unnecessary line

2021-06-15 19:37 UTC, michaelavs approved these changes
This looks good to me!

2021-06-17 20:09 UTC, anissa111 approved these changes
This looks good!

2021-06-21 19:38 UTC, merged