ce_3_1 with Contour
NCAR/GeoCAT-examples pull request #468
Opened 2022-07-06 17:50 UTC by doqhne

Creates NCL example ce_3_1 using geocat-viz Contour function. Includes link to previous version that does not use Contour.

[Previous script](https://geocat-examples.readthedocs.io/en/v2022.5.0/gallery/Contours/NCL_ce_3_1.html#sphx-glr-gallery-contours-ncl-ce-3-1-py)

New version of plot using Contour:
![ce_3_1_python](https://user-images.githubusercontent.com/99711690/177611821-4e8c559f-e897-4b5f-bc1a-a8fc6c56893e.png)

2022-07-20 18:54 UTC, anissa111 approved these changes

2022-07-20 18:57 UTC, anissa111 commented
Wait I missed something here. Let me do a quick edit and then I'll merge

2022-07-20 19:10 UTC, anissa111 commented
@hCraker @michaelavs I've introduced an updated "warning" message for experimental scripts here. We'll need to update other scripts to match, but I suggest doing that in a dedicated PR.

2022-07-20 19:55 UTC, hCraker requested changes
Some of the links aren't formatted right (Sphinx uses a strange syntax rather than markdown), and I recommended a way to make a nicely formatted and highly visible warning on the website. Once these suggestions are merged, I think this is good to go!

2022-07-20 19:55 UTC, hCraker commented on Gallery/Contours/NCL_ce_3_1.py
> +Note:
```suggestion
.. Warning::
```
If you use this header, you can make a nicely formatting warning in an orange box. It's really hard to miss and would be good to use here.

2022-07-20 19:55 UTC, hCraker commented on Gallery/Contours/NCL_ce_3_1.py
> +    See the geocat-viz experimental documentation for the functionality in this script [here](https://geocat-viz.readthedocs.io/en/experimental/).
```suggestion
    This is an experimental version of the script. Go to the `latest <https://geocat-examples.readthedocs.io/en/latest/gallery/Contours/NCL_ce_3_1.html>`_ version for the stable version.

    See the geocat-viz experimental documentation for the functionality in this script `here <https://geocat-viz.readthedocs.io/en/experimental/>`_.
```

Fix for link formatting

2022-07-21 16:56 UTC, hCraker approved these changes

2022-07-21 17:05 UTC, anissa111 commented
> Some of the links aren't formatted right (Sphinx uses a strange syntax rather than markdown), and I recommended a way to make a nicely formatted and highly visible warning on the website. Once these suggestions are merged, I think this is good to go!

Ah I forgot about that, thanks for the catch @hCraker!

2022-07-21 17:44 UTC, merged